
services:
  monitoring_service:
    build: .
    container_name: pump_monitoring_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - influxdb_monitor
    env_file: .env
    networks:
      - pump_network

  influxdb_monitor:
    image: influxdb:2.8
    container_name: pump_influxdb_monitor
    ports:
      - "8087:8086"
    env_file: .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - monitor_influx_data:/var/lib/influxdb2
    networks:
      - pump_network



volumes:
  monitor_influx_data:

networks:
  pump_network:
    external: true